# Generated by Django 3.0.4 on 2020-03-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trophy',
            options={'verbose_name_plural': 'trophies'},
        ),
    ]
