# Generated by Django 3.0.4 on 2020-03-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cups', '0002_auto_20200312_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophy',
            name='weight',
            field=models.PositiveIntegerField(default=1000, help_text='in g'),
            preserve_default=False,
        ),
    ]
