# Generated by Django 3.0.4 on 2020-03-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cups', '0003_trophy_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('trophies', models.ManyToManyField(to='cups.Trophy')),
            ],
        ),
    ]
