# Generated by Django 3.0.4 on 2020-03-12 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cups', '0004_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cups.Season')),
            ],
        ),
    ]
