# Generated by Django 3.0.5 on 2020-04-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cups', '0005_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.PositiveIntegerField(help_text='year season ended'),
        ),
    ]
